"""add password

Revision ID: 77ae0e093f4d
Revises: 925e37cb32b2
Create Date: 2026-03-01 17:20:32.314740

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '77ae0e093f4d'
down_revision: Union[str, Sequence[str], None] = '925e37cb32b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
